// "use client";
import { Inter } from "next/font/google";
import "./globals.css";
import React, { Suspense, lazy } from 'react';

const Back_ = lazy(() => import('./home/page'));
const Nav_ = lazy(() => import('./navbar/page'));

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{metadata.title}</title>
      </head>
      <body>
        <main>
          <Suspense fallback={<div>Loading...</div>}>
            <Nav_ />
            <Back_ />
          </Suspense>
          {children}
        </main>
      </body>
    </html>
  );
}
